MongoDB : find()
  docs = db.collection_name.find({})
  for doc in docs
  print (doc)
  MongoDB : find_one ()
    doc = db.collection_name.find_one({"student_id": "1007"})
    print(doc["student_id"])
    doc = db.collection_name.find_one({"first_name": "Emma"})
    print(doc["first_name"])
    doc = db.collection_name.find_one({"last_name": "Lopez Valdez"})
    print(doc["last_name"])
    
    MongoDB : find_one ()
      doc =db.collection_name.find_one({"student_id" : "1008"})
      print(doc["student_id])
      doc = db.collection_name.find_one({"first_name": "Zoe"})
      print(doc["first_name"])
      doc = db.collection_name.find_one({"last_name": "Lopez"})
      print(doc["last_name"])
      
      MongoDB : find_one ()
      doc =db.collection_name.find_one({"student_id" : "1009"})
      print(doc["student_id])
      doc = db.collection_name.find_one({"first_name": "Antonio"})
      print(doc["first_name"])
      doc = db.collection_name.find_one({"last_name": "Lopez"})
      print(doc["last_name"])

                MongoDB: insert ()
                docs = db.collection_name.insert({})
                for doc in docs
                print (doc)
                MongoDB: insert_one ()
                  doc= db.collection_name.insert_one({"student_id": "1010"})
                  print(doc["student_id"])
                  doc = db.collection_name.insert_one({"first_name": "Gigi"})
                  print(doc["first_name"])
                  doc = db.collection_name.insert_one({"last_name": "Lopez"})
                  print(doc["last_name"])
                 
                                       MongoDB : find_one ()
                                         doc = db.collection_name.find_one({"student_id": "1010"})
                                         print(doc["student_id"])
                                         doc = db.collection_name.find_one({"first_name": "Gigi"})
                                         print(doc["first_name"])
                                         doc = db.collection_name.find_one({"last_name": "Lopez"})
                                         print(doc["last_name"])
               
                MongoDB: delete ()
                docs = db.collection_name.delete({})
                for doc in docs
                print (doc)
                MongoDB: delete_one ()
                  doc= db.collection_name.delete_one({"student_id": "1010"})
                  doc = db.collection_name.delete_one({"first_name": "Gigi"})
                  doc = db.collection_name.delete_one({"last_name": "Lopez"})
                
MongoDB : find()
  docs = db.collection_name.find({})
  for doc in docs
  print (doc)
  MongoDB : find_one ()
    doc = db.collection_name.find_one({"student_id": "1007"})
    print(doc["student_id"])
    doc = db.collection_name.find_one({"first_name": "Emma"})
    print(doc["first_name"])
    doc = db.collection_name.find_one({"last_name": "Lopez Valdez"})
    print(doc["last_name"])
    
    MongoDB : find_one ()
      doc =db.collection_name.find_one({"student_id" : "1008"})
      print(doc["student_id])
      doc = db.collection_name.find_one({"first_name": "Zoe"})
      print(doc["first_name"])
      doc = db.collection_name.find_one({"last_name": "Lopez"})
      print(doc["last_name"])
      
      MongoDB : find_one ()
      doc =db.collection_name.find_one({"student_id" : "1009"})
      print(doc["student_id])
      doc = db.collection_name.find_one({"first_name": "Antonio"})
      print(doc["first_name"])
      doc = db.collection_name.find_one({"last_name": "Lopez"})
      print(doc["last_name"])
                
