MongoDB : find()
  docs = db.collection_name.find({})
  for doc in docs
  print (doc)
  MongoDB : find_one ()
    doc = db.collection_name.find_one({"student_id": "1007"})
    print(doc["student_id"])
    doc = db.collection_name.find_one({"first_name": "Emma"})
    print(doc["first_name"])
    doc = db.collection_name.find_one({"last_name": "Lopez"})
    print(doc["last_name"])
    
    MongoDB : find_one ()
      doc =db.collection_name.find_one({"student_id" : "1008"})
      print(doc["student_id])
      doc = db.collection_name.find_one({"first_name": "Zoe"})
      print(doc["first_name"])
      doc = db.collection_name.find_one({"last_name": "Lopez"})
      print(doc["last_name"])
      
      MongoDB : find_one ()
      doc =db.collection_name.find_one({"student_id" : "1009"})
      print(doc["student_id])
      doc = db.collection_name.find_one({"first_name": "Antonio"})
      print(doc["first_name"])
      doc = db.collection_name.find_one({"last_name": "Lopez"})
      print(doc["last_name"])
